name: ci

on:
  push:
    branches:
      - main

jobs:
  
  test:
    strategy:
      fail-fast: false
      matrix:
        - {
            os: ubuntu-latest,
            cxx: g++-13
          }
        - {
            os: windows-latest,
            cxx: cl.exe
          }
    runs-on: ${{ matrix.os }}


    steps:
    - uses: actions/checkout@v4
    - uses: lukka/get-cmake@latest

    - name: configure
      env:
        CXX: ${{ matrix.cxx }}
      shell: pwsh
      run: cmake "--preset=ci"

    - name: build
      shell: pwsh
      run: cmake --build --preset=ci

    - name: test
      shell: pwsh
      run: ctest --preset=ci