name: ci

on:
  push:
    branches:
      - main

jobs:
  
  test:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: ubuntu-latest,
              cxx: g++-13
            }
          - {
              os: ubuntu-latest,
              cxx: clang++-15
            }
          - {
              os: windows-latest,
              cxx: cl.exe
            }
          - {
              os: windows-latest,
              cxx: g++
            }
    runs-on: ${{ matrix.config.os }}


    steps:
    - uses: actions/checkout@v4
    - uses: lukka/get-cmake@latest

    - name: configure
      shell: pwsh
      env: { CXX: ${{ matrix.config.cxx }}}
      run: cmake --preset=ci

    - name: build
      shell: pwsh
      run: cmake --build --preset=ci

    - name: test
      shell: pwsh
      run: ctest --preset=ci