name: ci

on:
  push:
    branches:
      - main

jobs:
  
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: lukka/get-cmake@latest

    - name: install static analzers
      if: matrix.os == 'ubuntu-latest'
      run: >-
        sudo apt-get install clang-tidy -y -q
        clang-tidy --version
      
    
    - name: setup multitooltask
      if: matrix.os == 'windows-2022'
      run: |
        Add-Content "$env:GITHUB_ENV" 'UseMultiToolTask=true'
        Add-Content "$env:GITHUB_ENV" 'EnforceProcessCountAcrossBuilds=true'

    - name: configure
      shell: pwsh
      run: cmake "--preset=dev"

    - name: build
      shell: pwsh
      run: cmake --build --preset=dev

    - name: test
      shell: pwsh
      run: ctest --preset=dev