name: ci

on:
  push:
    branches:
      - main

jobs:
  
  test:
    strategy:
      fail-fast: false
    matrix:
      os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    if: matrix.os == 'ubuntu-latest'
      env: {CXX: "g++-13"}

    steps:
    - uses: actions/checkout@v4
    - uses: lukka/get-cmake@latest

    - name: configure
      shell: pwsh
      run: cmake "--preset=ci"

    - name: build
      shell: pwsh
      run: cmake --build --preset=ci

    - name: test
      shell: pwsh
      run: ctest --preset=ci